### ISSUE TITLE
Allow for simple GraphQL introspection queries to Magento for search filtering

### ISSUE THREAD

**Issue by kevin-mitchell** [adobe/commerce-cif-magento-graphql#11]
### User Story
As a user, I want to be able to make simple introspection queries against Magento to learn about which facets or filters Magento supports filtering on.

### Description & Motivation
Magento 2.3.4 exposes a number of new features through the GraphQL services. One in particular is the ability to filter (or "facet") search results, but because of the dynamic nature of Magento's attribute system we need to be able to find out information about available attributes through GraphQL's introspection feature. 

In order to support dynamic filtering of search results we need to be able to make such introspection queries against Magento's GraphQL API.

### Deliverables
We need to provide a base deserializer and supporting classes to allow for the introspection query to be made. This includes the supporting response classes (e.g. `InputField`) to use as output from the deserializer because unfortunately these are not autogenerated by the GraphQL generator it seems. 

### Acceptance Criteria
This project should be capable of producing a query for filters as well as providing a means to deserialize the result into a useful set of models for use in calling system (more than likely commerce components).

### Verification Steps
We should be able to use these classes in a `GraphQLClient` to make a introspection query for the attribute filter metadata.

**Comment by cjelger** [comment]
Closed by #14
